server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: apigateway
    static_configs:
      - targets: [localhost]
        labels:
          job: apigateway
          service: apigateway
          __path__: /var/log/app/apigateway.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: auth-service
    static_configs:
      - targets: [localhost]
        labels:
          job: auth-service
          service: auth
          __path__: /var/log/app/auth.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: role-service
    static_configs:
      - targets: [localhost]
        labels:
          job: role-service
          service: role
          __path__: /var/log/app/role.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: user-service
    static_configs:
      - targets: [localhost]
        labels:
          job: user-service
          service: user
          __path__: /var/log/app/user.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: category-service
    static_configs:
      - targets: [localhost]
        labels:
          job: category-service
          service: category
          __path__: /var/log/app/category.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: cashier-service
    static_configs:
      - targets: [localhost]
        labels:
          job: cashier-service
          service: cashier
          __path__: /var/log/app/cashier.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: merchant-service
    static_configs:
      - targets: [localhost]
        labels:
          job: merchant-service
          service: merchant
          __path__: /var/log/app/merchant.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: order-item-service
    static_configs:
      - targets: [localhost]
        labels:
          job: order-item-service
          service: order-item
          __path__: /var/log/app/order-item.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: order-service
    static_configs:
      - targets: [localhost]
        labels:
          job: order-service
          service: order
          __path__: /var/log/app/order.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: product-service
    static_configs:
      - targets: [localhost]
        labels:
          job: product-service
          service: product
          __path__: /var/log/app/product.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

  - job_name: transaction-service
    static_configs:
      - targets: [localhost]
        labels:
          job: transaction-service
          service: transaction
          __path__: /var/log/app/transaction.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            caller: caller
      - labels:
          level:
      - output:
          source: msg

 