global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - rules/golang-runtime-alerts.yaml
  - rules/kafka-exporter-alerts.yaml
  - rules/node-exporter-alerts.yaml
  - rules/otel-collector-alerts.yaml
  
  - rules/apigateway-alerts.yaml          
  - rules/email-service-alerts.yaml
  - rules/auth-service-alerts.yaml        
  - rules/role-service-alerts.yaml        
  - rules/user-service-alerts.yaml         
  - rules/category-service-alerts.yaml     
  - rules/cashier-service-alerts.yaml      
  - rules/merchant-service-alerts.yaml     
  - rules/order-item-service-alerts.yaml   
  - rules/order-service-alerts.yaml        
  - rules/product-service-alerts.yaml      
  - rules/transaction-service-alerts.yaml  

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          application: 'Otel Collector'
          environment: 'production'

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
        labels:
          application: 'Kafka Exporter'
          environment: 'production'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          application: 'Node Exporter'
          environment: 'production'

  - job_name: 'apigateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['apigateway:8091']
        labels:
          application: 'API Gateway'
          environment: 'production'

  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth:8081']
        labels:
          application: 'Auth Service'
          environment: 'production'

  - job_name: 'role-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['role:8082']
        labels:
          application: 'Role Service'
          environment: 'production'

  - job_name: 'user-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['user:8083']
        labels:
          application: 'User Service'
          environment: 'production'

  - job_name: 'category-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['category:8084']
        labels:
          application: 'Category Service'
          environment: 'production'

  - job_name: 'cashier-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cashier:8085']
        labels:
          application: 'Cashier Service'
          environment: 'production'

  - job_name: 'merchant-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['merchant:8086']
        labels:
          application: 'Merchant Service'
          environment: 'production'

  - job_name: 'order-item-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['order-item:8087']
        labels:
          application: 'Order Item Service'
          environment: 'production'

  - job_name: 'order-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['order:8088']
        labels:
          application: 'Order Service'
          environment: 'production'

  - job_name: 'product-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['product:8089']
        labels:
          application: 'Product Service'
          environment: 'production'

  - job_name: 'transaction-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['transaction:8090']
        labels:
          application: 'Transaction Service'
          environment: 'production'

