apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: pointofsale
spec:
  selector:
    app: auth
  ports:
    - name: http-metrics
      port: 8081
      targetPort: 8081
    - name: grpc
      port: 50051
      targetPort: 50051
  type: ClusterIP
