apiVersion: v1
kind: Service
metadata:
  name: category
  namespace: pointofsale
spec:
  selector:
    app: category
  ports:
    - name: http-metrics
      port: 8084
      targetPort: 8084
    - name: grpc
      port: 50054
      targetPort: 50054
  type: ClusterIP
