apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: pointofsale
data:
  APP_ENV: "kubernetes"
  DB_DRIVER: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "pointofsale"
  POSTGRES_DB: "pointofsale"
  DB_MAX_OPEN_CONNS: "50"
  DB_MAX_IDLE_CONNS: "10"
  DB_CONN_MAX_LIFETIME: "30m"
  DB_SEEDER: "true"
  APP_LOGGER: "production"

  OTEL_ENDPOINT: "otel-collector.pointofsale.svc.cluster.local:4317"
  KAFKA_BROKERS: "kafka.pointofsale.svc.cluster.local:9092"

  GRPC_AUTH_ADDR: auth.pointofsale.svc.cluster.local:50051
  GRPC_ROLE_ADDR: role.pointofsale.svc.cluster.local:50052
  GRPC_USER_ADDR: user.pointofsale.svc.cluster.local:50053
  GRPC_CATEGORY_ADDR: category.pointofsale.svc.cluster.local:50054
  GRPC_CASHIER_ADDR: cashier.pointofsale.svc.cluster.local:50055
  GRPC_MERCHANT_ADDR: merchant.pointofsale.svc.cluster.local:50056
  GRPC_ORDERITEM_ADDR: orderitem.pointofsale.svc.cluster.local:50057
  GRPC_ORDER_ADDR: order.pointofsale.svc.cluster.local:50058
  GRPC_PRODUCT_ADDR: product.pointofsale.svc.cluster.local:50059
  GRPC_TRANSACTION_ADDR: transaction.pointofsale.svc.cluster.local:50060

  GRPC_AUTH_PORT: "50051"
  GRPC_ROLE_PORT: "50052"
  GRPC_USER_PORT: "50053"
  GRPC_CATEGORY_PORT: "50054"
  GRPC_CASHIER_PORT: "50055"
  GRPC_MERCHANT_PORT: "50056"
  GRPC_ORDERITEM_PORT: "50057"
  GRPC_ORDER_PORT: "50058"
  GRPC_PRODUCT_PORT: "50059"
  GRPC_TRANSACTION_PORT: "50060"

  REDIS_DB_AUTH: "0"
  REDIS_DB_ROLE: "1"
  REDIS_DB_USER: "2"
  REDIS_DB_CATEGORY: "3"
  REDIS_DB_CASHIER: "4"
  REDIS_DB_MERCHANT: "5"
  REDIS_DB_ORDERITEM: "6"
  REDIS_DB_ORDER: "7"
  REDIS_DB_PRODUCT: "8"
  REDIS_DB_TRANSACTION: "9"

  METRIC_AUTH_ADDR: "8081"
  METRIC_ROLE_ADDR: "8082"
  METRIC_USER_ADDR: "8083"
  METRIC_CATEGORY_ADDR: "8084"
  METRIC_CASHIER_ADDR: "8085"
  METRIC_MERCHANT_ADDR: "8086"
  METRIC_ORDERITEM_ADDR: "8087"
  METRIC_ORDER_ADDR: "8088"
  METRIC_PRODUCT_ADDR: "8089"
  METRIC_TRANSACTION_ADDR: "8090"
  METRIC_APIGATEWAY: "8091"
