apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: pointofsale
spec:
  selector:
    app: jaeger
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
    - name: grpc
      port: 14250
      targetPort: 14250
  type: LoadBalancer
