apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: pointofsale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        fsGroup: 10001
        runAsUser: 10001
        runAsGroup: 10001
      initContainers:
        - name: fix-permission
          image: busybox:1.35
          command: ["sh", "-c"]
          args:
            - |
              echo "[INIT] Setting ownership for /loki"
              mkdir -p /loki
              chown -R 10001:10001 /loki
          volumeMounts:
            - name: storage
              mountPath: /loki
          securityContext:
            runAsUser: 0
            privileged: true
      containers:
        - name: loki
          image: grafana/loki:2.9.0
          args:
            - -config.file=/etc/loki/local-config.yaml
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: /loki
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: config
          configMap:
            name: loki-config
            items:
              - key: loki-config.yaml
                path: local-config.yaml
        - name: storage
          persistentVolumeClaim:
            claimName: loki-data-pvc
