apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant
  namespace: pointofsale
spec:
  replicas: 2
  selector:
    matchLabels:
      app: merchant
  template:
    metadata:
      labels:
        app: merchant
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: init-log-permission
          image: busybox:1.35
          command: ["sh", "-c"]
          args:
            - |
              echo "[INIT] Setting ownership for /var/log/app"
              chown -R 1000:1000 /var/log/app
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/app
          securityContext:
            runAsUser: 0

        - name: wait-for-kafka
          image: busybox:1.35
          command: ["sh", "-c"]
          args:
            - |
              echo "[INIT] Waiting for Kafka to be ready (TCP)..."
              until nc -z pointofsale-service.svc.cluster.local 9092; do
                echo "Kafka is not ready yet. Retrying in 5 seconds..."
                sleep 5
              done
              echo "[INIT] Kafka is ready!"
      containers:
        - name: merchant
          image: merchant-pointofsale-service:1.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 8056
            - containerPort: 50056
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8085
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/app
      volumes:
        - name: app-logs
          persistentVolumeClaim:
            claimName: app-logs-pvc
