apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: pointofsale
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: migrate-pointofsale-service:1.0
          workingDir: /app
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
