apiVersion: v1
kind: Service
metadata:
  name: order_item
  namespace: pointofsale
spec:
  selector:
    app: order_item
  ports:
    - name: http-metrics
      port: 8087
      targetPort: 8087
    - name: grpc
      port: 50057
      targetPort: 50057s
  type: ClusterIP
