apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: pointofsale
spec:
  selector:
    app: otel-collector
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: http
      port: 4318
      targetPort: 4318
    - name: metrics
      port: 13133
      targetPort: 13133
    - name: prometheus
      port: 8889
      targetPort: 8889
  type: ClusterIP
