apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: pointofsale
data:
  otel-collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

      prometheus:
        config:
          scrape_configs:
            - job_name: "otel-collector"
              scrape_interval: 5s
              static_configs:
                - targets: ["localhost:8888"]
            - job_name: "kafka-exporter"
              scrape_interval: 5s
              static_configs:
                - targets: ["kafka-exporter:9308"]
            - job_name: "auth-service"
              metrics_path: "/metrics"
              static_configs:
                - targets: ["auth:8081"]
                  labels:
                    application: "Auth Service"
                    environment: "production"
            - job_name: "merchant-service"
              metrics_path: "/metrics"
              static_configs:
                - targets: ["merchant:8084"]
                  labels:
                    application: "Merchant Service"
                    environment: "production"
            - job_name: "card-service"
              metrics_path: "/metrics"
              static_configs:
                - targets: ["card:8083"]
                  labels:
                    application: "Card Service"
                    environment: "production"
            - job_name: "saldo-service"
              metrics_path: "/metrics"
              static_configs:
                - targets: ["saldo:8086"]
                  labels:
                    application: "Saldo Service"
                    environment: "production"
            - job_name: "role-service"
              metrics_path: "/metrics"
              static_configs:
                - targets: ["role:8082"]
                  labels:
                    application: "Role Service"
                    environment: "production"
            - job_name: "topup-service"
              metrics_path: "/metrics"
              static_configs:
                - targets: ["topup:8087"]
                  labels:
                    application: "Topup Service"
                    environment: "production"
            - job_name: "transaction-service"
              metrics_path: "/metrics"
              static_configs:
                - targets: ["transaction:8088"]
                  labels:
                    application: "Transaction Service"
                    environment: "production"
            - job_name: "transfer-service"
              metrics_path: "/metrics"
              static_configs:
                - targets: ["transfer:8089"]
                  labels:
                    application: "Transfer Service"
                    environment: "production"
            - job_name: "user-service"
              metrics_path: "/metrics"
              static_configs:
                - targets: ["user:8085"]
                  labels:
                    application: "User Service"
                    environment: "production"
            - job_name: "email-service"
              metrics_path: "/metrics"
              static_configs:
                - targets: ["email:8080"]
                  labels:
                    application: "Email Service"
                    environment: "production"
            - job_name: "withdraw-service"
              metrics_path: "/metrics"
              static_configs:
                - targets: ["withdraw:8090"]
                  labels:
                    application: "Withdraw Service"
                    environment: "production"



    processors:
      batch:

    exporters:
      otlp:
        endpoint: "jaeger:4317"
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:8889"

    extensions:
      health_check:
      pprof:
      zpages:

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]

        metrics:
          receivers: [otlp, prometheus]
          processors: [batch]
          exporters: [prometheus]

        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
