apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: pointofsale
spec:
  selector:
    app: product
  ports:
    - name: http-metrics
      port: 8089
      targetPort: 8089
    - name: grpc
      port: 50059
      targetPort: 50059
  type: ClusterIP
