apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: pointofsale
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 0
      containers:
        - name: promtail
          image: grafana/promtail:2.9.0
          args:
            - -config.file=/etc/promtail/config.yaml
          ports:
            - name: http-metrics
              containerPort: 9080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: app-logs
              mountPath: /var/log/app
              readOnly: true
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          readinessProbe:
            httpGet:
              path: /ready
              port: 9080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ready
              port: 9080
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: promtail-config
            items:
              - key: promtail-config.yaml
                path: config.yaml
        - name: app-logs
          persistentVolumeClaim:
            claimName: app-logs-pvc
        - name: tmp
          emptyDir: {}
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
