apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: payment-gateway
type: Opaque
stringData:
  DB_USERNAME: "DRAGON"
  DB_PASSWORD: "DRAGON"

  POSTGRES_USER: "DRAGON"
  POSTGRES_PASSWORD: "DRAGON"

  DB_URL: "postgres://$(DB_USERNAME):$(DB_PASSWORD)@postgres:5432/PAYMENT_GATEWAY"

  GF_SECURITY_ADMIN_PASSWORD: "admin"
  
  SECRET_KEY: "yantopedia"
  REDIS_PASSWORD: "dragon_knight"

  SMTP_USER: "julius.davis@ethereal.email"
  SMTP_PASS: "4vWXpZfTMPAazhVZFU"
