apiVersion: v1
kind: Service
metadata:
  name: transaction
  namespace: pointofsale
spec:
  selector:
    app: transaction
  ports:
    - name: http-metrics
      port: 8090
      targetPort: 8090
    - name: grpc
      port: 50060
      targetPort: 50060
  type: ClusterIP
