apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: pointofsale
spec:
  selector:
    app: zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: 2181
  type: ClusterIP
